/**
 * Export helper (F-0020): produces a portable graph.json + minimal Dockerfile +
 * docker-compose.yml. PURE — returns the artifacts, performs NO disk I/O (F-DM1).
 * The committed evidence under roadmap/evidence/F-0020/ is captured once and is NOT
 * regenerated by a run; emitting at module/runtime dirtied the tree and raced under
 * parallel `node --test` (the flake the --test-concurrency=1 band-aid masked).
 * Zero-dependency TypeScript module.
 */

import { DEFAULT_MODEL } from './models.ts';

export interface ExportGraph {
  nodes: Array<{
    id: string;
    type: string;
    label: string;
    position: { x: number; y: number };
    model?: string;
    prompt?: string;
    estimatedCost?: number;
  }>;
  edges: Array<{ source: string; target: string }>;
}

/**
 * Minimal graph compatible with F-0019 shape.
 * nodes: id/type/label + optional position/model/prompt/estimatedCost
 * edges: source/target
 */
export function minimalGraph(): ExportGraph {
  return {
    nodes: [
      {
        id: 'n-start',
        type: 'start',
        label: 'Receive request',
        position: { x: 0, y: 0 },
        model: 'none',
        prompt: '',
        estimatedCost: 0
      },
      {
        id: 'n-process',
        type: 'process',
        label: 'Execute core task',
        position: { x: 300, y: 0 },
        model: DEFAULT_MODEL,
        prompt: 'demo export',
        estimatedCost: 0.01
      }
    ],
    edges: [
      { source: 'n-start', target: 'n-process' }
    ]
  };
}

export function dockerfileContent(): string {
  // node base, COPY graph, healthcheck
  return `FROM node:20-alpine
WORKDIR /app
COPY graph.json .
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 CMD node -e "process.exit(0)" || exit 1
`;
}

export function dockerComposeContent(): string {
  // DEMO_MODE + health (healthcheck)
  return `version: '3.8'
services:
  forge:
    build: .
    environment:
      - DEMO_MODE=1
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 3s
      retries: 3
`;
}

export interface ExportResult {
  graph: ExportGraph;
  dockerfile: string;
  dockerCompose: string;
  /** Human-readable summary of what was exported (relocated from the removed CLI's stdout). */
  summary: string;
}

/**
 * exportArtifacts(): build the three artifacts and return them. No disk writes — a caller
 * that wants files on disk writes the returned values to a path it owns (e.g. a gitignored
 * tmp/ dir), never into roadmap/evidence/.
 */
export function exportArtifacts(): ExportResult {
  const g = minimalGraph();
  const artifacts = ['graph.json', 'Dockerfile', 'docker-compose.yml'] as const;
  return {
    graph: g,
    dockerfile: dockerfileContent(),
    dockerCompose: dockerComposeContent(),
    summary: `exported ${artifacts.join(', ')}`,
  };
}
